name: 'firebase-hosting-preview-action'
description: 'Firebase Hosting Preview'
author: 'Jason Miller (https://github.com/developit)'
runs:
  using: 'node12'
  main: 'action.min.js'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  firebase-token:
    description: 'Firebase CI auth token (run "firebase login:ci")'
    required: true
  build-script:
    description: 'A script to run that builds your project'
    default: 'npm run build'
  use-web-tld:
    description: 'Use .web.app suffix instead of .firebaseapp.com?'