name: 'firebase-hosting-preview-action'
description: 'Firebase Hosting Preview'
author: 'Jason Miller (https://github.com/developit)'
runs:
  using: 'node12'
  main: 'action.min.js'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: false
  firebase-token:
    description: 'Firebase CI auth token (run "firebase login:ci")'
    required: true
  build-script:
    description: 'A script to run that builds your project'
    default: 'npm run build'
    required: false
  channel-ttl:
    description: 'How long should a preview live?'
    default: '7d'
    required: false