name: 'firebase-hosting-preview-action'
description: 'Firebase Hosting Preview'
author: 'Jason Miller (https://github.com/developit) and Firebase'
runs:
  using: 'node12'
  main: 'action.min.js'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: false
  firebase-service-account:
    description: 'Firebase service account JSON'
    required: true
  channel-ttl:
    description: 'How long should a preview live? See the preview channels docs for options'
    default: '7d'
    required: false