name: Deploy Preview

on: [pull_request]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: npm run build
      - uses: ./
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          firebase-service-account: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channel-ttl: 30d
          project-id: jeff-test-699d3
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
