name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: npm run build
      - uses: ./
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          channelId: live
          projectId: action-hosting-deploy-demo
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
